app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  retry-specification:
    back-off-type: fixed
    max-attempts: 6
    delay: 10000
    jitter: 0.5
    codes: 429, 500, 501, 502, 503, 504
  rate-limiter:
    is-working: true
    limit-per-minute: 100

spring:
  application:
    name: scrapper

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
